### ISSUE TITLE
Cannot compile MacOS due to SDL errors (both x64 and Silicon)

### ISSUE THREAD

**Issue by estefan3112** [qmc2/qmc2-mame-fe#29]
Hi Rene, suddenly I cannot compile on Intel plus Silicon Macs. Despite the SDL framework being installed (both Framework and Homebrew), the compile fails with strange SDL errors (excerpt below). 

So I cannot compile on any platform currently. Must be due to SDL upgrades.

Cheers, Stefan

(...)
In file included from src/about.cpp:9:
/Library/Frameworks/SDL2.framework/Headers/SDL.h:32:10: fatal error: 'SDL2/SDL_main.h' file not found
#include <SDL2/SDL_main.h>
(...)
In file included from src/joystick.h:11:
/Library/Frameworks/SDL2.framework/Headers/SDL.h:32:10: fatal error: 'SDL2/SDL_main.h' file not found
#include <SDL2/SDL_main.h>
(...)
In file included from src/welcome.cpp:17:
In file included from src/options.h:17:
In file included from src/joystick.h:11:
/Library/Frameworks/SDL2.framework/Headers/SDL.h:32:10: fatal error: 'SDL2/SDL_main.h' file not found
#include <SDL2/SDL_main.h>
         ^~~~~~~~~~~~~~~~~
In file included from src/options.cpp:24:
In file included from src/options.h:17:
In file included from src/joystick.h:11:
/Library/Frameworks/SDL2.framework/Headers/SDL.h:32:10: fatal error: 'SDL2/SDL_main.h' file not found
#include <SDL2/SDL_main.h>

It goes on like that...

**Comment by qmc2** [comment]
> /Library/Frameworks/SDL2.framework/Headers/SDL.h:32:10: fatal error: 'SDL2/SDL_main.h' file not found

Have you even installed SDL2?

**Comment by estefan3112** [comment]
Yes of course, latest versions of SDL2, both the Framework from the SDL site and the Homebrew packages. Used to work before, wll check again.

**Comment by qmc2** [comment]
To be more precise: You seem to have installed something in the the wrong way. It finds the frameworks header but this one somehow want SDL_main.h, which can't be found. Something is wrong with your SDL2 installation, not a QMC2 issue.

**Comment by estefan3112** [comment]
Dear Rene, there are currently two issues in the MacOS compiles that I could verify:

1. SDL: By coincidence I figured out that the code compiles nicely with an older SDL Framework release 2.0.20 of January 2022. I did not check all versions since then, but with the last SDL Framework release 2.26.1, the compile fails with the above errors. This applies to both Intel and Silicon Macs.
2. A recurring problem in QMake: The Apple Silicon Build misses -spec macx-clang-arm64 and fails with an error on macx-clang. After manually adding the right spec to the qmake line, it configures and compiles correctly.

As always happy to help, I could also test the SDL Frameworks backwards if that would make any difference...apparently some change in the SDL framework causes this error.

Best, Stefan

**Comment by estefan3112** [comment]
Add on: Ok, it stopped working with SDL 2.24.0, actually the first one with the new numbering scheme...

**Comment by estefan3112** [comment]
Dear Rene, may I suggests to re-open this issue: A comparison of the Makefile.qmakes shows sigificant differences, so something is going on there.

I opened a thread in the SDL Developer Forum, where your contribution would probably be very helpful:
https://discourse.libsdl.org/t/macos-fatal-error-sdl2-sdl-main-h-file-not-found-since-sdl-2-24-0/42029

Cheers! Stefan :-)

**Comment by qmc2** [comment]
I'm really unsure what to answer or contribute. It seems to be a Qt 5 qmake issue then? Dunno. I read all of the thread at discourse.libsdl.org but anything than irritation is not left :).
